import { ChecklistCategory } from '@/types';

export const INITIAL_CHECKLIST_DATA: ChecklistCategory[] = [
  {
    category: "Desktop QA (Chrome Primary)",
    sections: [
      {
        sectionId: "header-navigation",
        sectionTitle: "Header & Navigation",
        items: [
          { id: "hn-1", text: "Logo displays correctly and links to homepage", checked: false },
          { id: "hn-2", text: "Navigation menu items all visible and aligned properly", checked: false },
          { id: "hn-3", text: "Dropdown menus (if applicable) display correctly on hover", checked: false },
          { id: "hn-4", text: "Navigation links work and go to correct pages", checked: false },
          { id: "hn-5", text: "Active/current page indicator displays", checked: false },
          { id: "hn-6", text: "Header sticky/fixed behavior works as intended", checked: false },
          { id: "hn-7", text: "Contact info (phone/email) displays and is clickable", checked: false },
          { id: "hn-8", text: "CTAs in header are prominent and styled correctly", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "homepage-layout",
        sectionTitle: "Homepage Layout",
        items: [
          { id: "hl-1", text: "Hero section displays properly (image, text overlay, CTA)", checked: false },
          { id: "hl-2", text: "All sections load and display in correct order", checked: false },
          { id: "hl-3", text: "Spacing between sections is consistent", checked: false },
          { id: "hl-4", text: "Content alignment is correct (left/center/right)", checked: false },
          { id: "hl-5", text: "No overlapping elements", checked: false },
          { id: "hl-6", text: "White space is appropriate (not too cramped or too sparse)", checked: false },
          { id: "hl-7", text: "Background colors/images display correctly", checked: false },
          { id: "hl-8", text: "Page width is consistent (no horizontal scrolling)", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "typography-text",
        sectionTitle: "Typography & Text",
        items: [
          { id: "tt-1", text: "Font families consistent throughout site", checked: false },
          { id: "tt-2", text: "Heading hierarchy is clear (H1, H2, H3 sizing)", checked: false },
          { id: "tt-3", text: "Body text is readable (appropriate size, line height)", checked: false },
          { id: "tt-4", text: "Text color has sufficient contrast with background", checked: false },
          { id: "tt-5", text: "No awkward line breaks or orphaned words", checked: false },
          { id: "tt-6", text: "Bulleted/numbered lists format correctly", checked: false },
          { id: "tt-7", text: "Text doesn't overflow containers", checked: false },
          { id: "tt-8", text: "Links are visually distinguishable from regular text", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "images-media",
        sectionTitle: "Images & Media",
        items: [
          { id: "im-1", text: "All images load (no broken image icons)", checked: false },
          { id: "im-2", text: "Images are high quality (not pixelated or blurry)", checked: false },
          { id: "im-3", text: "Images maintain proper aspect ratio (not stretched/squished)", checked: false },
          { id: "im-4", text: "Alt text present (check a few images)", checked: false },
          { id: "im-5", text: "Background images display correctly", checked: false },
          { id: "im-6", text: "Icons render properly", checked: false },
          { id: "im-7", text: "Videos/embedded media load and display correctly", checked: false },
          { id: "im-8", text: "Image file sizes reasonable (not causing slow loads)", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "buttons-ctas",
        sectionTitle: "Buttons & CTAs",
        items: [
          { id: "bc-1", text: "All buttons styled consistently", checked: false },
          { id: "bc-2", text: "Button text is readable and clear", checked: false },
          { id: "bc-3", text: "Hover states work and are visually distinct", checked: false },
          { id: "bc-4", text: "Button sizing is appropriate (not too small/large)", checked: false },
          { id: "bc-5", text: "CTAs stand out from surrounding content", checked: false },
          { id: "bc-6", text: "Button alignment is correct", checked: false },
          { id: "bc-7", text: "Disabled states (if any) display correctly", checked: false },
          { id: "bc-8", text: "Icon buttons have clear purpose", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "forms",
        sectionTitle: "Forms",
        items: [
          { id: "f-1", text: "Form fields display correctly and consistently", checked: false },
          { id: "f-2", text: "Labels are clear and properly aligned", checked: false },
          { id: "f-3", text: "Input field sizing is appropriate", checked: false },
          { id: "f-4", text: "Placeholder text is visible and helpful", checked: false },
          { id: "f-5", text: "Required field indicators display", checked: false },
          { id: "f-6", text: "Error messages display properly", checked: false },
          { id: "f-7", text: "Submit button is prominent and clear", checked: false },
          { id: "f-8", text: "Form spacing and alignment is clean", checked: false },
          { id: "f-9", text: "Dropdown menus display all options", checked: false },
          { id: "f-10", text: "Checkbox/radio buttons styled and functional", checked: false },
          { id: "f-11", text: "Correct recipients are on forms (confirm with Client Success Team)", checked: false },
          { id: "f-12", text: "Proper thank you page displayed upon completion", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "footer",
        sectionTitle: "Footer",
        items: [
          { id: "ft-1", text: "Footer sections organized and aligned", checked: false },
          { id: "ft-2", text: "All footer links visible and work", checked: false },
          { id: "ft-3", text: "Contact information displays correctly", checked: false },
          { id: "ft-4", text: "Social media icons present and styled", checked: false },
          { id: "ft-5", text: "Copyright year is current", checked: false },
          { id: "ft-6", text: "Footer spans full width of page", checked: false },
          { id: "ft-7", text: "Footer background/styling consistent with site", checked: false },
          { id: "ft-8", text: "Newsletter signup (if present) displays correctly", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "interior-pages",
        sectionTitle: "Interior Pages (check 3-5 key pages)",
        items: [
          { id: "ip-1", text: "Page titles/headers display correctly", checked: false },
          { id: "ip-2", text: "Breadcrumbs (if present) work and display", checked: false },
          { id: "ip-3", text: "Content layout is clean and organized", checked: false },
          { id: "ip-4", text: "Sidebar (if present) displays correctly", checked: false },
          { id: "ip-5", text: "All page-specific images load", checked: false },
          { id: "ip-6", text: "Content sections are properly aligned", checked: false },
          { id: "ip-7", text: "Page-specific CTAs are prominent", checked: false },
          { id: "ip-8", text: "Consistent header/footer across all pages", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "overall-visual-consistency",
        sectionTitle: "Overall Visual Consistency",
        items: [
          { id: "ov-1", text: "Color scheme consistent throughout site", checked: false },
          { id: "ov-2", text: "Brand colors used correctly", checked: false },
          { id: "ov-3", text: "Design elements consistent across pages", checked: false },
          { id: "ov-4", text: "Spacing and padding consistent", checked: false },
          { id: "ov-5", text: "Visual hierarchy clear on all pages", checked: false },
          { id: "ov-6", text: "No jarring visual transitions between pages", checked: false },
          { id: "ov-7", text: "Site feels cohesive and professional", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
    ],
  },
  {
    category: "Mobile QA (Responsive View)",
    sections: [
      {
        sectionId: "mobile-navigation",
        sectionTitle: "Mobile Navigation",
        items: [
          { id: "mn-1", text: "Hamburger menu icon displays clearly", checked: false },
          { id: "mn-2", text: "Menu opens/closes smoothly", checked: false },
          { id: "mn-3", text: "Menu items all visible when expanded", checked: false },
          { id: "mn-4", text: "Menu text is readable (not too small)", checked: false },
          { id: "mn-5", text: "Close button/X is visible and works", checked: false },
          { id: "mn-6", text: "Logo displays correctly in mobile header", checked: false },
          { id: "mn-7", text: "Mobile menu doesn't overlap content", checked: false },
          { id: "mn-8", text: "Dropdowns (if any) work in mobile menu", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-layout-spacing",
        sectionTitle: "Mobile Layout & Spacing",
        items: [
          { id: "ml-1", text: "Content stacks properly (single column)", checked: false },
          { id: "ml-2", text: "No horizontal scrolling required", checked: false },
          { id: "ml-3", text: "Images scale to fit screen width", checked: false },
          { id: "ml-4", text: "Text is readable without zooming", checked: false },
          { id: "ml-5", text: "Touch targets are appropriately sized (min 44x44px)", checked: false },
          { id: "ml-6", text: "Spacing between elements is adequate for touch", checked: false },
          { id: "ml-7", text: "Sections maintain visual hierarchy", checked: false },
          { id: "ml-8", text: "Content doesn't feel cramped", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-hero-header",
        sectionTitle: "Mobile Hero/Header Section",
        items: [
          { id: "mh-1", text: "Hero image displays and scales properly", checked: false },
          { id: "mh-2", text: "Hero text is readable on mobile", checked: false },
          { id: "mh-3", text: "Hero CTA is prominent and tappable", checked: false },
          { id: "mh-4", text: "No important content cut off at fold", checked: false },
          { id: "mh-5", text: "Background images position correctly", checked: false },
          { id: "mh-6", text: "Text overlays maintain readability", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-typography",
        sectionTitle: "Mobile Typography",
        items: [
          { id: "mt-1", text: "Font sizes appropriate for mobile", checked: false },
          { id: "mt-2", text: "Headings scale down appropriately", checked: false },
          { id: "mt-3", text: "Line length comfortable for reading", checked: false },
          { id: "mt-4", text: "No text overflow or cut-off", checked: false },
          { id: "mt-5", text: "Links are tappable (not too close together)", checked: false },
          { id: "mt-6", text: "Text contrast sufficient on mobile", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-images-media",
        sectionTitle: "Mobile Images & Media",
        items: [
          { id: "mm-1", text: "Images load on mobile", checked: false },
          { id: "mm-2", text: "Images don't exceed screen width", checked: false },
          { id: "mm-3", text: "Image quality maintained (not overly compressed)", checked: false },
          { id: "mm-4", text: "No distorted/stretched images", checked: false },
          { id: "mm-5", text: "Carousels/sliders work with touch", checked: false },
          { id: "mm-6", text: "Videos display and are playable", checked: false },
          { id: "mm-7", text: "Gallery layouts work on mobile", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-buttons-forms",
        sectionTitle: "Mobile Buttons & Forms",
        items: [
          { id: "mbf-1", text: "Buttons are large enough to tap easily", checked: false },
          { id: "mbf-2", text: "Button text is fully visible", checked: false },
          { id: "mbf-3", text: "Form fields are appropriately sized", checked: false },
          { id: "mbf-4", text: "Keyboard doesn't obscure form fields", checked: false },
          { id: "mbf-5", text: "Dropdown menus are usable on mobile", checked: false },
          { id: "mbf-6", text: "Submit buttons are prominent", checked: false },
          { id: "mbf-7", text: "No buttons cut off at screen edges", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-footer",
        sectionTitle: "Mobile Footer",
        items: [
          { id: "mft-1", text: "Footer content stacks properly", checked: false },
          { id: "mft-2", text: "All footer links are tappable", checked: false },
          { id: "mft-3", text: "Social icons appropriately sized", checked: false },
          { id: "mft-4", text: "Contact info displays clearly", checked: false },
          { id: "mft-5", text: "Footer doesn't have horizontal scroll", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
      {
        sectionId: "mobile-specific-issues",
        sectionTitle: "Mobile-Specific Issues",
        items: [
          { id: "ms-1", text: "Portrait orientation works correctly", checked: false },
          { id: "ms-2", text: "Landscape orientation works correctly", checked: false },
          { id: "ms-3", text: "Pop-ups/modals display properly on mobile", checked: false },
          { id: "ms-4", text: "Fixed/sticky elements don't cover content", checked: false },
          { id: "ms-5", text: "Click-to-call links work for phone numbers", checked: false },
          { id: "ms-6", text: "Email links open mail client", checked: false },
          { id: "ms-7", text: "Maps/location features work", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
    ],
  },
  {
    category: "Cross-Browser Spot Check (Safari, Chrome, Firefox)",
    sections: [
      {
        sectionId: "cross-browser-criteria",
        sectionTitle: "Cross-Browser Testing",
        items: [
          { id: "cb-1", text: "Layout renders correctly", checked: false },
          { id: "cb-2", text: "Fonts display properly", checked: false },
          { id: "cb-3", text: "Images load", checked: false },
          { id: "cb-4", text: "No major visual issues", checked: false },
        ],
        issuesFound: { text: "", images: [] },
        completed: false,
      },
    ],
  },
];

